config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { passwords: 'users/passwords', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'home_page#show'

  get '/404', to: 'error#not_found'

  resource :setting, only: [:edit]
  resource :address, only: [:update]
  resource :review, only: [:create]
  resource :cart, only: [:create, :show] do
    post :delete_book, on: :member
    post :check_coupon, on: :member
    post :update_quantity_books_by_one, on: :member
    post :update_prices, on: :member
  end

  devise_scope :user do
    resource :check_login, only: [:show] do
      post :quick_register, on: :member
      post :login, on: :member
    end
  end

  resource :checking, only: [:show, :update]
  resources :books, only: [:index, :show]
  resources :orders, only: [:index, :show]
end

app/models/order.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: orders
#
#  id           :bigint           not null, primary key
#  completed_at :datetime
#  delivered_at :datetime
#  number       :string
#  status       :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  coupon_id    :bigint
#  delivery_id  :bigint
#  user_id      :bigint
#
# Indexes
#
#  index_orders_on_coupon_id    (coupon_id)
#  index_orders_on_delivery_id  (delivery_id)
#  index_orders_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (delivery_id => deliveries.id)
#  fk_rails_...  (user_id => users.id)
#
class Order < ApplicationRecord
  include AASM

  scope :in_progress, lambda {
                        where(status: %i[checking_address checking_delivery checking_payment checking_confirm
                                         checking_complete])
                      }
  scope :in_queue, -> { where(status: :complete) }

  aasm column: :status, whiny_transitions: false, timestamps: true do
    state :cart, initial: true
    state :checking_address, :checking_delivery, :checking_payment, :checking_confirm, :checking_complete, :complete,
          :in_delivery, :delivered, :canceled

    event :check_address do
      transitions from: :cart, to: :checking_address
    end

    event :check_delivery do
      transitions from: :checking_address, to: :checking_delivery
    end

    event :check_payment do
      transitions from: :checking_delivery, to: :checking_payment
    end

    event :check_confirm do
      transitions from: :checking_payment, to: :checking_confirm
    end

    event :check_complete do
      transitions from: :checking_confirm, to: :checking_complete
    end

    event :bought do
      transitions from: :checking_complete, to: :complete
    end

    event :back_to_address do
      transitions from: :checking_confirm, to: :checking_address
    end

    event :back_to_delivery do
      transitions from: :checking_confirm, to: :checking_delivery
    end

    event :back_to_payment do
      transitions from: :checking_confirm, to: :checking_payment
    end

    event :to_in_delivery do
      transitions to: :in_delivery
    end

    event :to_canceled do
      transitions to: :canceled
    end

    event :to_delivered do
      transitions from: :in_delivery, to: :delivered
    end
  end

  belongs_to :coupon, optional: true
  belongs_to :user, optional: true
  belongs_to :delivery, optional: true
  has_one :payment, dependent: :destroy

  has_one :billing_address, as: :addressed, dependent: :destroy
  has_one :shipping_address, as: :addressed, dependent: :destroy

  has_many :saved_books, dependent: :destroy
  has_many :books, through: :saved_books
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = FilteredOrdersQuery.new(params[:filter], current_user).call
  end

  def show
    @order = Order.find(params[:id])
  end
end

app/views/orders/index.haml
%main.container.general-main-wrap
  - if @orders.nil?
    %h1.general-title-margin.text-center= I18n.t(:no_orders)
    = link_to books_path do
      %button.btn.btn-default.mb-20.hidden-xs.center-block= I18n.t(:to_shop)
  - else
    %h1.mt-0.mb-25= I18n.t(:my_orders)
    %p.lead.small.mb-10.visible-xs= I18n.t(:sort_by)
    .dropdowns.dropdown.general-order-dropdown
      %a.dropdown-toggle.lead.small{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
        = params[:filter] || I18n.t(:waiting_process)
        %i.fa.fa-angle-down.dropdown-icon.pull-right
      %ul.dropdown-menu
        %li
          = link_to(I18n.t(:waiting_process), orders_path(filter: :complete))
        %li
          = link_to(I18n.t(:in_delivery),  orders_path(filter: :in_delivery))
        %li
          = link_to(I18n.t(:delivered),  orders_path(filter: :delivered))
        %li
          = link_to(I18n.t(:canceled),  orders_path(filter: :canceled))
    .hidden-xs.mb-res-50
      %table.table.table-hover
        %thead
          %tr
            %th
              %span.in-grey-600= I18n.t(:number)
            %th
              %span.in-grey-600= I18n.t(:completed_at)
            %th
              %span.in-grey-600= I18n.t(:status)
            %th
              %span.in-grey-600= I18n.t(:total)
        %tbody
          - @orders.each do |order|
            %tr
              %td
                = link_to order_path(order.id) do
                  %span.general-order-number= order.number
              %td
                %span.in-grey-900.font-16.fw-300= I18n.l(order.completed_at, format: :long)
              %td
                %span.font-16.in-grey-900.fw-300= order.decorate.status
              %td
                %strong.font-16= number_to_currency(order.decorate.order_total_price, locale: :fr)

app/views/orders/show.haml
%main.container.general-main-wrap
  %h1.general-title-margin= @order.decorate.title
  .row.mb-20
    .col-sm-3
      %h3.general-subtitle= I18n.t(:shipping_address)
      = render('layouts/partials/address_data', address: @order.shipping_address || @order.billing_address, link: true)
    .col-sm-3
      %h3.general-subtitle= I18n.t(:billing_address)
      = render('layouts/partials/address_data', address: @order.billing_address, link: true)
    = render('layouts/partials/shipments_data', delivery: @order.delivery, order: @order, link: true)
    = render('layouts/partials/payment_data', payment: @order.payment, link: true)
  = render('layouts/partials/order_books', order: @order)
  .text-center.general-text-right
    %p.in-gold-500.font-18= I18n.t(:order_summary)
    %table.general-summary-table.general-summary-table-right.general-text-right
      = render('layouts/partials/total_order_price', order: @order)