config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { passwords: 'users/passwords', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'home_page#show'

  get '/404', to: 'error#not_found'

  resource :setting, only: [:edit]
  resource :address, only: [:update]
  resource :review, only: [:create]
  resource :cart, only: [:create, :show] do
    post :delete_book, on: :member
    post :check_coupon, on: :member
    post :update_quantity_books_by_one, on: :member
    post :update_prices, on: :member
  end

  devise_scope :user do
    resource :check_login, only: [:show] do
      post :quick_register, on: :member
      post :login, on: :member
    end
  end

  resource :checking, only: [:show, :update]
  resources :books, only: [:index, :show]
  resources :orders, only: [:index, :show]
end

app/controllers/check_logins_controller.rb
# frozen_string_literal: true

class CheckLoginsController < Devise::RegistrationsController
  before_action :permit_params, :route_after_sign_in

  def show
    @user = build_resource
  end

  def quick_register
    email = params[:user][:email]
    return redirect_to check_login_path, alert: I18n.t(:account_exist) if User.exists?(email: email)

    setup_user(email)
  end

  def login
    user = User.find_by(email: params[:user][:email])
    unless user&.valid_password?(params[:user][:password])
      return redirect_to check_login_path, alert: I18n.t(:'devise.failure.invalid', authentication_keys: 'email')
    end

    setup_cart(user)
    redirect_to checking_path, alert: I18n.t(:'devise.sessions.signed_in')
  end

  private

  def setup_cart(user)
    sign_in user
    cart = Order.find(session[:current_cart])
    cart.update(user_id: user.id)
    cart.check_address! if cart.cart?
  end

  def setup_user(email)
    user = User.new(email: email, password: Devise.friendly_token[0, 20])

    return redirect_to check_login_path, alert: I18n.t(:invalid_email) unless valid_email?(user)

    user.skip_confirmation!
    user.send_reset_password_instructions
    user.save
    setup_cart(user)
    redirect_to checking_path, alert: I18n.t(:'devise.sessions.signed_in')
  end

  def permit_params
    params.permit(:authenticity_token, user: %i[email password])
  end

  def route_after_sign_in
    cart = Order.find(session[:current_cart])
    cart.check_address! if cart.cart?
    redirect_to checking_path if user_signed_in?
  end

  def valid_email?(user)
    user.valid?
    return false unless user.errors[:email].empty?

    true
  end
end

app/views/check_logins/check.haml
%main.container
  .row
    .col-md-5.mb-40
      .text-center
        %h3.general-subtitle= I18n.t(:returing_customer)
        = link_to(user_facebook_omniauth_authorize_path, class: 'general-login-icon', id: 'facebook', method: :post) do
          %i.fab.fa-facebook-square{style: "font-size: 45px"}
        %p.general-login-text= I18n.t(:or)
      = simple_form_for @user, url: login_check_login_path(@user), html: {id: 'new-user-login'},  validate: true do |form|
        = render "devise/shared/error_messages", resource: @user
        .mb-40
          %p.mb-15= I18n.t(:login_with_password)
          = form.input :email, label: I18n.t(:enter_email), placeholder: I18n.t(:enter_email), input_html: {id: 'user_email_login'}
          = form.input :password, label: I18n.t(:password), placeholder: I18n.t(:password)
          = link_to(I18n.t(:forgot_password), new_password_path(@user), class: 'help-block in-gold-500')
        = form.button :submit, I18n.t(:login_with_password), class: 'btn btn-default mb-20'
    .col-md-5.col-md-offset-1.mb-60
      .text-center
        %h3.general-subtitle= I18n.t(:new_customer)
        = link_to(user_facebook_omniauth_authorize_path, class: 'general-login-icon', id: 'facebook', method: :post) do
          %i.fab.fa-facebook-square{style: "font-size: 45px"}
        %p.general-login-text= I18n.t(:or)
      = simple_form_for @user, url: quick_register_check_login_path(@user), html: {id: 'new-user-register'}, validate: true do |form|
        = render "devise/shared/error_messages", resource: @user
        .mb-40
          %p.mb-5= I18n.t(:quick_register)
          %p.general-info-text.font-12.mb-20= I18n.t(:can_create_password_later)
          = form.input :email, label: I18n.t(:enter_email), placeholder: I18n.t(:enter_email), input_html: {id: 'user_email_register'}
          = form.button :submit, I18n.t(:continue_to_checkout), class: 'btn btn-default mb-20'

app/views/check_logins/show.haml
%main.container
  .row
    .col-md-5.mb-40
      .text-center
        %h3.general-subtitle= I18n.t(:returing_customer)
        = link_to(user_facebook_omniauth_authorize_path, class: 'general-login-icon', id: 'facebook', method: :post) do
          %i.fab.fa-facebook-square{style: "font-size: 45px"}
        %p.general-login-text= I18n.t(:or)
      = simple_form_for @user, url: login_check_login_path(@user), html: {id: 'new-user-login'},  validate: true do |form|
        = render "devise/shared/error_messages", resource: @user
        .mb-40
          %p.mb-15= I18n.t(:login_with_password)
          = form.input :email, label: I18n.t(:enter_email), placeholder: I18n.t(:enter_email), input_html: {id: 'user_email_login'}
          = form.input :password, label: I18n.t(:password), placeholder: I18n.t(:password)
          = link_to(I18n.t(:forgot_password), new_password_path(@user), class: 'help-block in-gold-500')
        = form.button :submit, I18n.t(:login_with_password), class: 'btn btn-default mb-20'
    .col-md-5.col-md-offset-1.mb-60
      .text-center
        %h3.general-subtitle= I18n.t(:new_customer)
        = link_to(user_facebook_omniauth_authorize_path, class: 'general-login-icon', id: 'facebook', method: :post) do
          %i.fab.fa-facebook-square{style: "font-size: 45px"}
        %p.general-login-text= I18n.t(:or)
      = simple_form_for @user, url: quick_register_check_login_path(@user), html: {id: 'new-user-register'}, validate: true do |form|
        = render "devise/shared/error_messages", resource: @user
        .mb-40
          %p.mb-5= I18n.t(:quick_register)
          %p.general-info-text.font-12.mb-20= I18n.t(:can_create_password_later)
          = form.input :email, label: I18n.t(:enter_email), placeholder: I18n.t(:enter_email), input_html: {id: 'user_email_register'}
          = form.button :submit, I18n.t(:continue_to_checkout), class: 'btn btn-default mb-20'