config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { passwords: 'users/passwords', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'home_page#show'

  get '/404', to: 'error#not_found'

  resource :setting, only: [:edit]
  resource :address, only: [:update]
  resource :review, only: [:create]
  resource :cart, only: [:create, :show] do
    post :delete_book, on: :member
    post :check_coupon, on: :member
    post :update_quantity_books_by_one, on: :member
    post :update_prices, on: :member
  end

  devise_scope :user do
    resource :check_login, only: [:show] do
      post :quick_register, on: :member
      post :login, on: :member
    end
  end

  resource :checking, only: [:show, :update]
  resources :books, only: [:index, :show]
  resources :orders, only: [:index, :show]
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def create
    setup_cart
    flash[:alert] = I18n.t(:book_add_to_cart)
    redirect_back(fallback_location: book_path(params[:book_id]))
  end

  def show
    return unless session[:current_cart]

    @cart = Order.find_by(id: session[:current_cart])
    return session[:current_cart] = nil unless @cart

    @books = @cart.books
  end

  def delete_book
    SavedBook.where.not(status: :closed).where(book_id: params[:book_id]).destroy_all
    session[:quantity_books] -= 1
    check_empty_cart
    redirect_to cart_path, alert: I18n.t(:book_success_delete)
  end

  def check_coupon
    redirect_to cart_path, alert: CouponService.new(params[:coupon], session[:current_cart]).permit_coupon
  end

  def update_quantity_books_by_one
    CartService.new(params[:book_id], params[:quantity_books], session[:current_cart]).update_by_one(params[:direction])
    redirect_to cart_path
  end

  def update_prices
    cart = CartService.new(params[:book_id], params[:quantity_books], session[:current_cart])
    cart.update
    render json: cart.select
  end

  private

  def setup_cart
    cart = CartService.new(params[:book_id], params[:quantity_books], session[:current_cart]).create_or_update
    cart.update(user: current_user) unless cart.user
    setup_session(cart)
  end

  def setup_session(cart)
    session[:current_cart] = cart.id
    session[:quantity_books] = cart.books.count
  end

  def check_empty_cart
    cart = Order.find(session[:current_cart])
    return unless cart.books.empty?

    session[:current_cart] = nil
    session[:quantity_books] = 0
    cart.destroy
  end
end

app/views/carts/show.haml
%main.container.general-main-wrap
  - if session[:current_cart].nil? || @cart.nil?
    %h1.general-title-margin.text-center= I18n.t(:cart_empty)
    = link_to books_path do
      %button.btn.btn-default.mb-20.hidden-xs.center-block= I18n.t(:to_shop)
  - else
    %h1.general-title-margin= I18n.t(:cart)
    .hidden-xs
      %table.table.table-hover
        %tr.no-hover
          %th.col-pic.pl-0
            %span.in-grey-600= I18n.t(:product)
          %th.col-title
          %th.col-price
            %span.in-grey-600= I18n.t(:price)
          %th.col-quantity
            %span.in-grey-600= I18n.t(:quantity)
          %th.col-total
            %span.in-grey-600= I18n.t(:sub_total)
          %th.col-close
        - @books.each do |book|
          %tr
            %td
              .general-img-wrap-table
                = link_to book_path(book.id) do
                  %img.cart-img-shadow.pull-left{src: book.images.first.image(:small).url, alt: "design-book"}
            %td
              = link_to book_path(book.id) do
                %p.title= book.name
            %td
              %span.font-16.in-gold-500= number_to_currency(book.price, locale: :fr)
            %td
              .input-group
                = link_to update_quantity_books_by_one_cart_path(book_id: book.id, quantity_books: book.decorate.quantity(session[:current_cart]), direction: -1), method: :post, class: 'input-link' do
                  %i.fa.fa-minus.line-heaght-40
                %input.form-control.quantity-input.send{type: "text", value: "#{book.decorate.quantity(session[:current_cart])}"}
                %input#book_id{hidden: true, value: "#{book.id}"}
                = link_to update_quantity_books_by_one_cart_path(book_id: book.id, quantity_books: book.decorate.quantity(session[:current_cart]), direction: 1), method: :post, class: 'input-link' do
                  %i.fa.fa-plus.line-heaght-40
            %td
              %span.font-16.in-gold-500.sub-total= number_to_currency(book.price * book.decorate.quantity(session[:current_cart]), locale: :fr)
            %td
              = link_to delete_book_cart_path(book_id: book.id),  method: :post, class: 'close general-cart-close' do
                %span{'aria-hidden': "true"} &times;
    .general-order-wrap
      .row
        .col-sm-4
          = form_with url: check_coupon_cart_path do |form|
            .input-group.general-input-group
              %label.input-label= I18n.t(:enter_coupon)
              = form.text_field :coupon, class: 'form-control mb-30', placeholder: I18n.t(:enter_coupon)
              %div
                = form.submit I18n.t(:apply_coupon), class: 'btn btn-primary mr-5 mb-15'
        .col-sm-8
          .res-mr-200.text-center.general-text-right
            %p.in-gold-500.font-18= I18n.t(:order_summary)
            %table.general-summary-table.general-summary-table-right.general-text-right
              = render('layouts/partials/order_summary', order: @cart)
    = link_to check_login_path do
      %button.btn.btn-default.mb-20.hidden-xs.center-block= I18n.t(:checkout)