config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { passwords: 'users/passwords', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'home_page#show'

  get '/404', to: 'error#not_found'

  resource :setting, only: [:edit]
  resource :address, only: [:update]
  resource :review, only: [:create]
  resource :cart, only: [:create, :show] do
    post :delete_book, on: :member
    post :check_coupon, on: :member
    post :update_quantity_books_by_one, on: :member
    post :update_prices, on: :member
  end

  devise_scope :user do
    resource :check_login, only: [:show] do
      post :quick_register, on: :member
      post :login, on: :member
    end
  end

  resource :checking, only: [:show, :update]
  resources :books, only: [:index, :show]
  resources :orders, only: [:index, :show]
end

app/views/layouts/partials/_address_data.haml
%p.general-address
  = address.decorate.name
  = link_to checking_path(state: 'address') do
    - if link
      %span.general-edit= I18n.t(:edit)
  %br
  = address.address
  %br
  = address.decorate.city_zip
  %br
  = address.country
  %br
  = "Phone #{address.phone}"

app/views/layouts/partials/_bestsellers.haml
- bestsellers_books.each do |book|
  .col-sm-6.col-md-3
    .general-thumb-wrap
      .thumbnail.general-thumbnail
        %img.img-shadow.general-thumbnail-img{src:  book.images.first.image(:large).url, alt: "design-book"}
        .thumb-hover
          .general-thumb-link-wrap
            = link_to book_path(book.id), class: "thumb-hover-link" do
              %i.fas.fa-eye.thumb-icon{'aria-hidden': "true"}
            = link_to cart_path(book_id: book.id, quantity_books: 1), method: :post, class: 'thumb-hover-link' do
              %i.fas.fa-shopping-cart.thumb-icon
    .mb-35
      .clearfix
        %p.pull-right.font-16.in-gold-500= number_to_currency(book.price, locale: :fr)
        %p.title.mr-55= book.name
      %span.divider-sm
      = render('layouts/partials/authors_name', authors: book.authors)

app/views/layouts/partials/_checkout_steps.haml
%h1.general-title-margin= I18n.t(:checkout)
%ul.steps.list-inline
  %li.step{class: "#{active == I18n.t(:address) ? 'active': ''}"}
    %span.step-number 1
    %span.step-text.hidden-xs= I18n.t(:address)
  %li.step-divider
  %li.step{class: "#{active == I18n.t(:delivery) ? 'active': ''}"}
    %span.step-number 2
    %span.step-text.hidden-xs= I18n.t(:delivery)
  %li.step-divider
  %li.step{class: "#{active == I18n.t(:payment) ? 'active': ''}"}
    %span.step-number 3
    %span.step-text.hidden-xs= I18n.t(:payment)
  %li.step-divider
  %li.step{class: "#{active == I18n.t(:confirm) ? 'active': ''}"}
    %span.step-number 4
    %span.step-text.hidden-xs= I18n.t(:confirm)
  %li.step-divider
  %li.step{class: "#{active == I18n.t(:complete) ? 'active': ''}"}
    %span.step-number 5
    %span.step-text.hidden-xs= I18n.t(:complete)

app/views/layouts/partials/_errors.haml
- if errors.any?
  #error_explanation
    %ul
      - errors.each do |message|
        %li= message

app/views/layouts/partials/_flesh_messages.haml
- flash.each do |key, value|
  %div{class: "alert alert-#{key} general-login-text", style: "display: flex;justify-content: center;align-content: center;flex-wrap: wrap;flex-direction: column;"}
    = value
    %a.close{"data-dismiss" => "alert", href: "#", style: "margin: 0 auto"} x

app/views/layouts/partials/_footer.haml
%footer.navbar-inverse
  .container
    .row
      .col-sm-9
        %ul.list-inline.general-align.mb-25
          %li
            = link_to(I18n.t(:home), root_path, class: 'nav-link')
          %li
            = link_to(I18n.t(:shop), '/shop', class: 'nav-link')
          %li
            = link_to(I18n.t(:orders), '/orders', class: 'nav-link')
          %li
            = link_to(I18n.t(:settings), '/settings', class: 'nav-link')
      .col-sm-3
        %p.general-nav-mail= I18n.t(:email_support)
        %p.general-nav-number= I18n.t(:number_phone)
        %ul.list-inline.general-align
          %li
            = link_to('/facebook', class: 'nav-link') do
              %i.fab.fa-facebook-f{'aria-hidden': "true"}
          %li
            = link_to('/twitter', class: 'nav-link') do
              %i.fab.fa-twitter{'aria-hidden': "true"}
          %li
            = link_to('/google-plus', class: 'nav-link') do
              %i.fab.fa-google-plus{'aria-hidden': "true"}
          %li
            = link_to('/instagram', class: 'nav-link') do
              %i.fab.fa-instagram{'aria-hidden': "true"}

app/views/layouts/partials/_header.haml
%header.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.pull-left{type: "button", 'data-toggle': "collapse", 'data-target': "#navbar"}
        %span.sr-only
        %span.icon-bar
      = link_to(I18n.t(:title_store), root_path, class: 'navbar-brand')
    = link_to(cart_path, class: 'shop-link pull-right') do
      %span.shop-icon{style: session[:current_cart] ? '' : "background-color: #fff" }
        %span.shop-quantity= session[:quantity_books]
    #navbar.navbar-collapse.collapse.pl-30{'aria-expanded': "false"}
      - unless user_signed_in?
        %ul.nav.navbar-nav
          %li
            = link_to(I18n.t(:home), root_path)
          %li
            = link_to(I18n.t(:shop), books_path, data_toggle: "collapse", class: "article", type: 'button', aria_expanded: 'false', aria_controls: 'menu')
          %li
            = link_to(I18n.t(:log_in), new_session_path(User))
          %li
            = link_to(I18n.t(:sign_up), new_registration_path(User))
      - else
        %ul.nav.navbar-nav
          %li
            = link_to(I18n.t(:home), root_path)
          %li
            = link_to(I18n.t(:shop), books_path, data_toggle: "collapse", class: "article", type: 'button', aria_expanded: 'false', aria_controls: 'menu')
          %li.dropdown
            %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}= I18n.t(:my_account)
            %ul.dropdown-menu
              %li
                = link_to(I18n.t(:orders), orders_path)
              %li
                = link_to(I18n.t(:settings), edit_setting_path)
              %li.divider{role: "separator"}
              %li
                = link_to(I18n.t(:log_out), destroy_user_session_path, :method => :delete)

app/views/layouts/partials/_latest_books.haml
- books.each_with_index do |book, index|
  .item{ class: "#{'active' if index.zero?}" }
    .row
      .col-sm-5
        .general-img-wrap
          %img.img-shadow.general-thumbnail-img{src:  book.images.first.image(:large).url, alt: "design-book"}
      .col-sm-7
        .mb-60
          %h1= book.name
          %p.lead= book.description
          = render('layouts/partials/authors_name', authors: book.authors)
          .general-align
            = link_to cart_path(book_id: book.id, quantity_books: 1), method: :post do
              %button.btn-primary= I18n.t(:buy_now)

app/views/layouts/partials/_next_link.haml
!= pagy_next_link(pagy, text: I18n.t(:view_more), link_extra: 'id="next_link", class = "btn btn-primary"')

app/views/layouts/partials/_order_summary.haml
%tr
  %td
    %p.font-16= I18n.t(:sub_total_summary)
  %td
    %p.font-16.sub-total-order= number_to_currency(order.decorate.sub_total_price, locale: :fr)
%tr
  %td
    %p.font-16= I18n.t(:coupon_summary)
  %td
    %p.font-16.coupon= number_to_currency(order.decorate.discount, locale: :fr)
%tr
  %td
    %strong.font-18= I18n.t(:order_total_summary)
  %td
    %strong.font-18.order-total-price= number_to_currency(order.decorate.order_total_price, locale: :fr)

app/views/layouts/partials/_reviews.haml
.mb-80
  %h3= I18n.t(:write_review)
  %p.general-info-text= I18n.t(:score)
  .mb-15
    %ul.stars
      - BooksController::RATING_STARS_SIZE.times do |index|
        %li.star
          %i.fas.fa-star{id: index + 1}
  - if current_user
    = simple_form_for ReviewForm.new(Review.new), url: review_path, html: {class: 'row'} do |review|
      .col-md-8
        = review.input :title, label: I18n.t(:title), label_input: { class: 'control-label input-label in-grey-600'}, input_html: {id: 'title'}
        = review.input :message, as: :text, label: I18n.t(:review), label_input: { class: 'control-label input-label in-grey-600'}, input_html: {id: 'review', cols: 5, rows: 8}
        = review.input :stars, :as => :hidden, input_html: {value: 1}
        = review.input :book_id, :as => :hidden, input_html: {value: book_id}
        = review.input :user_id, :as => :hidden, input_html: {value: current_user ? current_user.id : 1}
        = review.button :submit, I18n.t(:post)
  .mb-80
    .rating-stars.text-center
    %h3.in-gold-500.mb-25= "#{I18n.t(:reviews)} #{reviews.length}"
    - reviews.each do |review|
      .general-message-wrap.divider-lg
        .clearfix
          %span.img-circle.logo-size.inlide-block.pull-left.logo-empty= review.user.decorate.image_letter
          .ml-70
            %div
              .general-message-date.hidden-xs= I18n.l(review.created_at, format: :custom_short)
              .max-260
                .general-message-verified= I18n.t(:verified_reviewer)
                .general-message-name= review.user.decorate.show_email_or_name
            .mb-15
              %ul.stars
                - BooksController::RATING_STARS_SIZE.times do |index|
                  %li.read-star
                    %i.fas.fa-star{class: "#{'clicked-stars' if index + 1 <= review.stars.to_i }"}
            %p= review.message

app/views/layouts/partials/_shipments_data.haml
.col-sm-3
  %h3.general-subtitle= I18n.t(:shipmets)
  %p.general-address
    = delivery.method
    = link_to checking_path(state: 'delivery') do
      - if link
        %span.general-edit= I18n.t(:edit)
    %br
    = number_to_currency(order.decorate.shipping, locale: :fr)

app/views/layouts/partials/_user_settings_email.haml
= simple_form_for current_user, url: user_registration_path(current_user.id), method: :put,
          html: { class: 'general-form-md', id: 'edit_user_email'} , validate: true do |form|
  = render('layouts/partials/errors', errors: params[:errors_email] || [])
  = form.input :email, label: I18n.t(:enter_email), name: 'email', placeholder: I18n.t(:enter_email), id: 'email',
            wrapper_html: { class: "form-group mb-35 #{'has-error' if params[:errors_email]}"}, hint: "#{params[:success_change_email]}"
  .text-center.general-text-align
    = form.button :submit, I18n.t(:save), name: 'email_button'

app/views/layouts/partials/_user_settings_password.haml
= simple_form_for current_user, url: user_password_path, html: { class: 'general-form-md divider-lg-bottom pb-25',
          id: 'edit_user_password'}, method: :put, validate: true do |form|
  = render('layouts/partials/errors', errors: params[:errors_password] || [])
  = form.hidden_field :reset_password_token
  = form.input :password, label: I18n.t(:old_password), name: 'password', placeholder: I18n.t(:old_password),
            input_html: {id: 'oldPassword'}, wrapper_html: { class: 'form-group mb-30'}
  = form.input :password, label: I18n.t(:new_password), name: 'password', placeholder: I18n.t(:new_password),
            input_html: {id: 'password'}, wrapper_html: { class: "form-group mb-30 #{'has-error' if params[:errors_password]}"}
  = form.input :password, label: I18n.t(:confirm_password), name: 'password', placeholder: I18n.t(:confirm_password),
            input_html: {id: 'confirmPassword'}, wrapper_html: { class: 'form-group mb-40'}
  .text-center.general-text-align
    = form.button :submit, I18n.t(:save), name: 'password_button'